blogApp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    
    path('', views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/', views.categorias_v, name='categoria'),
    #categoria_id es eñ parametro que recibira desde la base de datos por eso va entre corchetes
  
]

carroApp/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static

 #aqui agragamos la url de esta app (pueden haber varias apps)
app_name="carro"
urlpatterns = [
    
    path("agregar/<int:producto_id>/",views.agregar_producto,name="agregar"),
    path("eliminar/<int:producto_id>/",views.eliminar_producto,name="eliminar"),
    path("restar/<int:producto_id>/",views.restar_producto,name="restar"),
    path("limpiar/",views.limpiar_producto,name="limpiar"),

]

proyectoTiendaVirtual/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('serviciosApp.urls')),
    path('contactos/', include('contactoApp.urls')),
    path('blogs/', include('blogApp.urls')),
    path('tienda/', include('tiendaApp.urls')),
    path('carro/', include('carroApp.urls')),
    path('autenticacion/', include('authenticationApp.urls')),
    
    
    
    path('', include('TiendaVirtual.urls')),
    
    
    #path('TiendaVirtual/', include('TiendaVirtual.urls')) se podria hacer lo mism con otras aplicaciones
    #al raiz del pat se puede dejar vacia o
]

tiendaApp/urls.py
from django.urls import path
from tiendaApp import views

from django.conf.urls.static import static

 #aqui agragamos la url de esta app (pueden haber varias apps)

urlpatterns = [
    
    path('',views.tienda, name='Tienda'),

]

tiendaApp/models.py
from django.db import models


class categoriaProducto (models.Model):
    nombre=models.CharField(max_length=50)
    create=models.DateField(auto_now_add=True)
    update=models.DateField(auto_now=True)
    class Meta:
        verbose_name = 'categoriap'
        verbose_name_plural ='categoriasp'
        
    def __str__(self):
        return self.nombre
    
class producto (models.Model):
    nombrep=models.CharField(max_length=50)
    categoria=models.ForeignKey(categoriaProducto, on_delete=models.CASCADE)#el ondelete es para borrar en cascada junto a la lave foranea
    imagen=models.ImageField(upload_to='mediaTienda', null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    create=models.DateField(auto_now_add=True)
    update=models.DateField(auto_now=True)
    class Meta:
        verbose_name = 'producto'
        verbose_name_plural ='productos'
        
    def __str__(self):
        return self.nombrep

tiendaApp/views.py
from django.shortcuts import render
from tiendaApp.models import *

# Create your views here.
def tienda(request):
    products=producto.objects.all()#esto es para que nos muestre todos los post
    return render(request, "tienda/tienda.html",{'productos':products})#esto es para pasar el diccionario

tiendaApp/templates/carro/widget.html
<table class="table table-bordered " style="color: rgb(255, 255, 255);">

    <thead>

        <tr>
            <th colspan="3" class="text-center">

            </th>
        </tr>


        <tr>
            <th>producto</th>
            <th>cantidad </th>
            <th>suma </th>

        </tr>
    


    </thead>
    <tbody>
        {% if request.session.carro.items %}
         {%for key, value in request.session.carro.items %}
           <tr class="text-center">
               <td>{{value.nombre}}</td>
               <td>{{value.cantidad}}</td>
               <td>
                <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                <br>
                   {{value.precio}} $
               </td>
            </tr>

         {% endfor %}
        {% endif %}
        <tr>
        <td colspan="3">
            <div class=" alert alert-danger text-center">
                NO hay productos

            </div>

        </td>
    </tr>

    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                total: {{importe_total_carro}} $
            </td>
        </tr>
    </tfoot>
</table>